### ISSUE TITLE
The results are not consistent with those in the manuscript.

### ISSUE THREAD

**Issue by 670555467** [OCEAN-98/Incremental-Online-Adaptive-MADDPG-for-Network-Slicing-Resource-Management#1]
Hello, I have run 4to5_slices, why does it not match with the results in the manuscript, the results are dropping. Hope you can help answer the queries? Thanks

**Comment by 670555467** [comment]
> Hello, I have run 4to5_slices, why does it not match with the results in the manuscript, the results are dropping. Hope you can help answer the queries? Thanks

![training_4_5](https://github.com/OCEAN-98/Incremental-Online-Adaptive-MADDPG-for-Network-Slicing-Resource-Management/assets/92203808/aa379d84-4f7d-49a7-8d7a-e1c1ad62ede9)

**Comment by OCEAN-98** [comment]
Hi there, it never happened to me. It does have some variations with different training sessions, but shouldn't be like this. Will look into it. How about rest?

**Comment by 670555467** [comment]
> Hi there, it never happened to me. It does have some variations with different training sessions, but shouldn't be like this. Will look into it. How about rest?

Can you set a random seed and test it? I was surprised to see this result. The reward function value for 4_slicies, which I ran out to only about 0.18, didn't reach above 0.25.

**Comment by 670555467** [comment]
> Hi there, it never happened to me. It does have some variations with different training sessions, but shouldn't be like this. Will look into it. How about rest?

Hello, by looking at your code, are you defining slices for the number of NFV transfers, rather than traditional slices for services such as embb, urllc and mmtc?

**Comment by OCEAN-98** [comment]
Nope, no specific defined types of slices. Happens on the edges, only urllc considered, which not going to the core.

**Comment by 670555467** [comment]
> Hello, by looking at your code, are you defining slices for the number of NFV transfers, rather than traditional slices for services such as embb, urllc and mmtc?

Our objective is two-fold: (i) maximizing long-term network slicing benefits in terms of delay and energy consumption, and
(ii) adapting to slice number changes. What about this second advantage of not withdrawing to? Or did I not get the idea of the manuscript, I will again also continue to learn. Thank you very much for your prompt reply!

**Comment by OCEAN-98** [comment]
The main idea of the second is by inheriting the knowledge from previous model to save training cost.  I am not sure I understand correctly. Hope this answers.

**Comment by 670555467** [comment]
> The main idea of the second is by inheriting the knowledge from previous model to save training cost. I am not sure I understand correctly. Hope this answers.

I saw that the second advantage really felt new and so I did some serious studying. You could have phrased it in a different way and I think it makes more sense.
